### ISSUE TITLE
De-Ironman saved games?

### ISSUE THREAD

**Issue by ReedJessen** [Junuxx/tradeviz#8]
Hi Junuxx,

I came across this repo looking for a way to parse eu4 ironman save files.  It looks like you have started on this.   When I run your code, some of the gibberish seems to fall out but it's still gibberish.  

Are you still actively working on this? Do you think it's an achievable goal? What is your process for reverse engineering these files?

I would like to help out if you think I might be useful.  Maybe spin it out into it's own library.

Thoughts?

**Comment by Junuxx** [comment]
Hi Reed,

Thanks for your interest in my project! I haven't worked on this in a while
although it would be fun to get back into it.

The little progress I made was not original work, but based on someone
else's eu4parser, I just adapted it from D to Python.
This project's Github repo seems to be gone, but there is a backup of the
relevant file here
<https://coveralls.io/builds/2426040/source?filename=source%2Ftypes%2Fpackage.d>,
containing
a much more complete translation table. The author is Simon Sigurdhsson
<https://github.com/urdh/>, maybe he would be the one to ask further
questions about the reverse engineering process.

One the one hand, I think would be awesome for the modding community if we
could read Ironman files. And Paradox did choose to merely encode Ironman
files rather than actual encryption, so it's not like they really tried
hard to make it impossible to read.

On the other hand, the devs have removed several de-Ironman tricks/bugs
from the game before, and I think making a way to do this publicly
available could very well antagonize them. When I started on adapting this
eu4parser code in Tradeviz, my intention was to silently include the
ability to read Ironman files, to stay under some overeager moderator's
radar and not have my project taken down. Maybe I'm just paranoid, but it
might be something to think about.

There is also Ironmelt
<https://codeofwar.wbudziszewski.pl/2017/08/23/ironmelt-4-5/>, but I
haven't tried it. What do you think?

Best,

**Comment by ReedJessen** [comment]
Hi Junxx,

Yeah, I think we are on the same page. I don't really want to build anything to make it easy to cheat or break the game.  I love paradox games, there really the only genre of game that I keep coming back to.

For more context, I love paradox games because of the insanely difficult and complicated, yet achievable, achievements system. What I am building is a web app that allows a user to upload a ironman save file for the various paradox games (EU4 at first) and then it will return which achievements are still possible and/or actually practical to get given your current situation in the game.   EU4 has a feature that tells you your progress to certain achievements but doesn't tell you when they aren't possible anymore.  To build this, I need to parse the users upload to deserializeable form. 

I downloaded Ironmelt last night.  It seems to work well.  I didn't realize the save files were so huge!  I think a kludge for now might to just make a system call out to Ironmelt and return the parseable text.  That being said, I think the code at coveralls.io looks very compelling.  I would really like to get it working in python so that I have control over speed optimization rather than using Ironmelt. It may be enough to do a standalone python library.

Thanks for responding to me.  I will keep you in the loop.

**Comment by ReedJessen** [comment]
Closing this issue for now.  Will loop you in one way or another as I make more progress.  Thanks for the advice @Junuxx .
